name: Create Archive
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Files
        run: |
          cd vikinghug
          zip -r ../vikinghug.zip *

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: vikinghug.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
